### ISSUE TITLE
geoserver -  Unavailable authority factory: European Petroleum Survey Group

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2302]
Debian package with geoserver 18.06 from https://packages.georchestra.org/debian/pool/main/g/georchestra-geoserver/ seems buggy. 

GeoServer fails loading the EPSG database from `gt-epsg-hsql-18.5.jar` (which is present in WEB-INF/lib/)

```
2018-11-30 11:17:39,721 WARN [referencing.factory] - Unavailable authority factory: European Petroleum Survey Group
2018-11-30 11:17:39,734 WARN [org.geoserver] - Error decode epsg code: EPSG:4326
org.opengis.referencing.NoSuchAuthorityCodeException: No code "EPSG:4326" from authority "European Petroleum Survey Group" found for object of type "IdentifiedObject".
	at org.geotools.referencing.factory.AbstractAuthorityFactory.noSuchAuthorityCode(AbstractAuthorityFactory.java:875)
	at org.geotools.referencing.factory.PropertyAuthorityFactory.getWKT(PropertyAuthorityFactory.java:292)
	at org.geotools.referencing.factory.PropertyAuthorityFactory.createCoordinateReferenceSystem(PropertyAuthorityFactory.java:361)
	at org.geotools.referencing.factory.BufferedAuthorityFactory.createCoordinateReferenceSystem(BufferedAuthorityFactory.java:732)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:780)
	at org.geotools.referencing.factory.FallbackAuthorityFactory.createCoordinateReferenceSystem(FallbackAuthorityFactory.java:625)
	at org.geotools.referencing.factory.AuthorityFactoryAdapter.createCoordinateReferenceSystem(AuthorityFactoryAdapter.java:780)
	at org.geotools.referencing.factory.ThreadedAuthorityFactory.createCoordinateReferenceSystem(ThreadedAuthorityFactory.java:636)
	at org.geotools.referencing.DefaultAuthorityFactory.createCoordinateReferenceSystem(DefaultAuthorityFactory.java:177)
	at org.geotools.referencing.CRS.decode(CRS.java:517)
	at org.geotools.referencing.CRS.decode(CRS.java:440)
	at org.geoserver.config.util.XStreamPersister$SRSConverter.fromString(XStreamPersister.java:1356)
```

**Comment by landryb** [comment]
i've seen it recently (see irc logs from 28 august :) and iirc it was (in my case) some kind of mixup between `java.io.tmpdir` & `CATALINA_TMPDIR` where it tries to create the `Geotools/Databases/HSQL/v8.6.xx` hierarchy. In the end it started working again magically.....

**Comment by fvanderbiest** [comment]
Thanks for the hint !

Indeed, using ansible deployer, https://github.com/georchestra/ansible/blob/7f5ebb7ff668e270daadee95678bed3505fbee9c/roles/tomcat/templates/tomcat.service.j2#L14 sets `CATALINA_TMPDIR=/tmp/tomcat8-%i-tmp`

For some reason, `/tmp/tomcat8-georchestra-tmp` exists and filled with HSQL EPSG db, but `/tmp/tomcat8-geoserver-tmp` does not.

**Comment by fvanderbiest** [comment]
Fixed by changing line
`Environment=CATALINA_TMPDIR=/tmp/tomcat8-%i-tmp` into `Environment=CATALINA_TMPDIR=/srv/tmp/tomcat8-%i-tmp` and making sure these 3 directories exist before + belong to tomcat8.

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/ansible/commit/44d9dc9f120368bdea43c35be276a9ef9b2db62a on branch 18.06

**Comment by landryb** [comment]
So there were two tmpdirs (the one by default in `wheretomcatis/tmp`) and the one that was set with CATALINA_TMPDIR, and geoserver only works with the one by default because it's hardcoded somewhere in its code ?

Imo the bug is not fixed, just swept under the rug...;
