### ISSUE TITLE
CI - 20.1.4 images not generated due to errors

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3502]
[Console](https://github.com/georchestra/georchestra/actions/runs/1229738950), [mapfishapp](https://github.com/georchestra/georchestra/actions/runs/1229738954) & [extractorapp](https://github.com/georchestra/georchestra/actions/runs/1229738957) failed to build

**Comment by pmauduit** [comment]
for mapfishapp, it will take me an unreasonable amount of time to be able to rebuild, as my dev env is not compatible anymore with jsbuild. No quickwin for now.

**Comment by pmauduit** [comment]
extractorapp image is based on Jetty: https://github.com/georchestra/georchestra/blob/master/extractorapp/src/docker/Dockerfile which probably migrated to bullseye recently, in which the libgdal-java does not exist anymore (there is a reason for that, I can't find back the ticket from packages.debian.org, but it was breaking a lot of packages transitively depending on GDAL on some architectures suppoted by the project, where a JDK was not available - in the package list, there were at least opencv and some others well-known ones).

I'd go for disabling the `apt install libgdal-java` from the dockerfile as a quick win. I'm pretty sure the default geotools will also do the work quite fine.

**Comment by pmauduit** [comment]
mfapp: I can reproduce the failing test locally. I am wondering if it is worth investing time on it, if mfapp is EOL anyway. The main issue with this test is that we rely on geobretagne geoserver, a better approach would be to mock, and have the wfs responses as resources locally available instead. I took a look in this direction, but could not have something relevant in a reasonable amount of time.

btw, I pushed by hand the 3 images on docker-hub, resulting from the build from the 20.1.4 tag.

**Comment by pmauduit** [comment]
Being able to relaunch failing jobs should help (see https://github.com/georchestra/georchestra/pull/3572):

![image](https://user-images.githubusercontent.com/594335/150828084-aaf41422-93d4-4cf5-aaeb-9c5f6c088305.png)

**Comment by fvanderbiest** [comment]
`apt-get update && apt-get install -y libgdal-java gdal-bin` still failing on 20.1.x for extractorapp

**Comment by fvanderbiest** [comment]
> `apt-get update && apt-get install -y libgdal-java gdal-bin` still failing on 20.1.x for extractorapp
Fixed with 43b9a68d1de8a2208f3abe92d77b8a94867252f2
